import { Montserrat } from "next/font/google";
import "./globals.css";
import {StateContextProvider} from "@/components/contextProvider";
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // optional, include the weights you need
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={montserrat.variable}>
      <body
        className={`font-[var(--font-montserrat)] antialiased min-h-screen bg-background text-foreground bg-gray-900 md:px-4 max-w-[1800px] mx-auto overflow-x-hidden `}
        style={{ fontFamily: "Montserrat, sans-serif" }}
      >
        <StateContextProvider>
          <div className="md:pb-4 lg:pb-6 px-0 ">
            {children}
          </div>
        </StateContextProvider>
      </body>
    </html>
  );
}
