import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // optional, include the weights you need
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={montserrat.variable}>
      <body
        className={`font-[var(--font-montserrat)] antialiased min-h-screen bg-background text-foreground bg-gray-900`}
        style={{ fontFamily: "Montserrat, sans-serif" }}
      >
        <div className="px-6 lg:px-12">{children}</div>
      </body>
    </html>
  );
}
